# Generated by Django 5.0.14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reklam_icazesi',
            field=models.CharField(
                choices=[
                    ('default', 'Default / Limitsiz'),
                    ('limitsiz', 'Limitsiz'),
                    ('qadagan', 'Qadağan edilib'),
                ],
                default='default',
                max_length=20,
                verbose_name='Reklam icazəsi',
            ),
        ),
        migrations.CreateModel(
            name='Reklam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('ixtisas_fenni', models.CharField(max_length=150, verbose_name='İxtisas / Fənn')),
                ('sekil', models.ImageField(blank=True, null=True, upload_to='reklamlar/', verbose_name='Şəkil')),
                ('haqqinda_melumat', models.TextField(blank=True, max_length=600, null=True, verbose_name='Haqqında məlumat')),
                ('telefon_nomresi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nömrəsi')),
                ('yaradilma_tarixi', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('yenilenme_tarixi', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reklamlar',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='Sahib',
                )),
            ],
            options={
                'verbose_name': 'Reklam',
                'verbose_name_plural': 'Reklamlar',
                'ordering': ['-yenilenme_tarixi'],
            },
        ),
    ]
