# Generated by Django 5.0.14 on 2026-08-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reklam_and_reklam_icazesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklam',
            name='xususi_reklam',
            field=models.BooleanField(default=False, verbose_name='Xüsusi Reklam'),
        ),
    ]
