# Generated by Django 5.0.14 on 2026-08-28 15:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reklam_xususi_reklam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Tələbə', 'verbose_name_plural': 'Tələbələr'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='participants',
        ),
        migrations.AddField(
            model_name='student',
            name='activity_status',
            field=models.BooleanField(choices=[(True, 'Aktiv'), (False, 'Deaktiv')], default=True, verbose_name='Aktivlik statusu'),
        ),
        migrations.AddField(
            model_name='student',
            name='attendance_grades',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Davamiyyət Qiyməti'),
        ),
        migrations.AddField(
            model_name='student',
            name='firstname',
            field=models.CharField(default='', max_length=100, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='student',
            name='lastname',
            field=models.CharField(default='', max_length=100, verbose_name='Soyad'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='', max_length=150, verbose_name='Şifrə'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=150, unique=True, verbose_name='İstifadəçi adı'),
        ),
        migrations.CreateModel(
            name='ClassRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Tam adı')),
                ('participants', models.CharField(blank=True, choices=[('', '--------'), ('i/e', 'İştirak edir'), ('q/b', 'Qayıb'), ('ü/q', 'Üzrlü Qayıb')], default='', max_length=10, verbose_name='Davamiyyət')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='core.class', verbose_name='Cari sinif')),
            ],
            options={
                'verbose_name': 'Sinif Qeydiyyatı',
                'verbose_name_plural': 'Sinif Qeydiyyətləri',
                'ordering': ['full_name'],
            },
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.classrosterentry', verbose_name='Tələbə (Roster)'),
        ),
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_status', models.CharField(choices=[('', '--------'), ('i/e', 'İştirak edir'), ('q/b', 'Qayıb'), ('ü/q', 'Üzrlü Qayıb')], default='i/e', max_length=10, verbose_name='Davamiyyət')),
                ('evaluation_grade', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Qiymətləndirmə (0-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('class_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='core.class', verbose_name='Sinif')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='core.student', verbose_name='Tələbə')),
            ],
            options={
                'verbose_name': 'Tələbə-Sinif Qeydiyyatı',
                'verbose_name_plural': 'Tələbə-Sinif Qeydiyyətləri',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'class_assigned')},
            },
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='students', through='core.StudentClassEnrollment', to='core.class', verbose_name='Siniflər'),
        ),
    ]
