# Generated by Django 5.0.14 on 2026-08-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_student_options_remove_student_current_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['lastname', 'firstname'], 'verbose_name': 'Şagird', 'verbose_name_plural': 'Şagirdlər'},
        ),
        migrations.AlterModelOptions(
            name='studentclassenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Şagird-Sinif Qeydiyyatı', 'verbose_name_plural': 'Şagird-Sinif Qeydiyyətləri'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('', '--------'), ('i/e', 'İştirak edir'), ('q/b', 'Qayıb'), ('gecikir', 'Gecikir'), ('icazeli', 'İcazəli'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=20, verbose_name='Davamiyyət və Qiymətləndirmə'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.classrosterentry', verbose_name='Şagird (Roster)'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='core.student', verbose_name='Şagird'),
        ),
    ]
