# Generated by Django 5.0.14 on 2026-08-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Dərs', 'verbose_name_plural': 'Dərslər'},
        ),
    ]
