# Generated by Django 5.0.14 on 2026-08-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['date', 'start_time', 'id'], 'verbose_name': 'Dərs', 'verbose_name_plural': 'Dərslər'},
        ),
    ]
