# Generated by Django 5.0.14 on 2026-09-01 09:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_student_attendance_grades_and_lesson_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['lesson__date', 'student__full_name'], 'verbose_name': 'Davamiyyət / Qiymət', 'verbose_name_plural': 'Davamiyyət / Qiymətlər'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Dərs', 'verbose_name_plural': 'Dərslər'},
        ),
        migrations.AlterModelOptions(
            name='reklam',
            options={'ordering': ['-xususi_reklam', '-yenilenme_tarixi'], 'verbose_name': 'Reklam', 'verbose_name_plural': 'Reklamlar'},
        ),
        migrations.AlterModelOptions(
            name='studentclassenrollment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Şagird Sinif Qeydiyyatı', 'verbose_name_plural': 'Şagird Sinif Qeydiyyətləri'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-is_superuser', '-staff', 'username'], 'verbose_name': 'İstifadəçi', 'verbose_name_plural': 'İstifadəçilər'},
        ),
        migrations.AddField(
            model_name='class',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_classes', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan'),
        ),
        migrations.AddField(
            model_name='classrosterentry',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roster_entries', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lessons', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan'),
        ),
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan'),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Aktivləşmə tarixi'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan'),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deaktivləşmə tarixi'),
        ),
        migrations.AddField(
            model_name='user',
            name='lesson_link',
            field=models.URLField(blank=True, null=True, verbose_name='Xüsusi Dərs Linki'),
        ),
        migrations.AddField(
            model_name='user',
            name='teacher_creation_limit',
            field=models.IntegerField(default=0, verbose_name='Müəllim yaratma limiti'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('', '--------'), ('i/e', 'İştirak edir'), ('q/b', 'Qayıb'), ('gecikir', 'Gecikir'), ('icazəli', 'İcazəli'), ('ü/q', 'Üzrlü Qayıb'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.classrosterentry', verbose_name='Şagird (Qeydiyyat)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title_topic',
            field=models.CharField(max_length=250, verbose_name='Mövzu'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='ad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='haqqinda_melumat',
            field=models.TextField(blank=True, null=True, verbose_name='Haqqında məlumat'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='ixtisas_fenni',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='İxtisas / Fənn'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reklamlar', to=settings.AUTH_USER_MODEL, verbose_name='Sahib'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='soyad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='reklam',
            name='telefon_nomresi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon nömrəsi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='attendance_grades',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Davamiyyət Qiyməti (0-10)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Ad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Soyad'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=150, verbose_name='Şifrə'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='İstifadəçi adı'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='attendance_status',
            field=models.CharField(choices=[('', '--------'), ('i/e', 'İştirak edir'), ('q/b', 'Qayıb'), ('gecikir', 'Gecikir'), ('icazəli', 'İcazəli'), ('ü/q', 'Üzrlü Qayıb')], default='i/e', max_length=20, verbose_name='Davamiyyət Statusu'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='class_assigned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.class', verbose_name='Sinif'),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.student', verbose_name='Şagird'),
        ),
        migrations.AlterField(
            model_name='user',
            name='reklam_icazesi',
            field=models.CharField(choices=[('default', 'Varsayılan / Limitsiz'), ('limitsiz', 'Limitsiz'), ('qadagan', 'Qadağan edilib')], default='default', max_length=20, verbose_name='Reklam icazəsi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff',
            field=models.IntegerField(choices=[(1, 'Müəllim'), (2, 'Kurs-inzibatçısı'), (0, 'Digər')], default=0, verbose_name='Vəzifə'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Fənn'),
        ),
    ]
