# Generated by Django 5.0.14 on 2026-09-01 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_attendance_options_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1500, verbose_name='Rəy və təklif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
            ],
            options={
                'verbose_name': 'Rəy və Təklif',
                'verbose_name_plural': 'Rəylər və Təkliflər',
                'ordering': ['-created_at'],
            },
        ),
    ]
