# Generated by Django 5.0.14 on 2026-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_attendance_student_tracking_and_reklam_requirements'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('lesson', 'student'), name='unique_attendance_lesson_student'),
        ),
    ]
